apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: nl-amis-visualization
  labels:
    app: grafana
    version: "8.4.4"
    environment: visualization
spec:
  ports:
    - nodePort: 30300
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
    version: "8.4.4"
    environment: visualization
  sessionAffinity: None
  type: NodePort