apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: nl-amis-logging
spec:
  selector:
    matchLabels:
      app: kibana
      version: "7.0.0"
      environment: logging
  template:
    metadata:
      labels:
        app: kibana
        version: "7.0.0"
        environment: logging
    spec:
      containers:
      - name: kibana-container
        image: docker.elastic.co/kibana/kibana:7.0.0
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch-service.nl-amis-logging:9200
        ports:
        - containerPort: 5601