apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: nl-amis-logging
  labels:
    app: kibana
    version: "7.0.0"
    environment: logging
spec:
  type: NodePort
  selector:
    app: kibana
    version: "7.0.0"
    environment: logging
  ports:
  - nodePort: 30601
    port: 5601
    targetPort: 5601