apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: nl-amis-logging
  labels:
    app: elasticsearch
    version: "7.0.0"
    environment: logging
spec:
  type: NodePort
  selector:
    app: elasticsearch
    version: "7.0.0"
    environment: logging
  ports:
  - nodePort: 30200
    port: 9200
    targetPort: 9200