apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: nl-amis-logging
  labels:
    app: logstash
    version: "1.0"
    environment: logging
spec:
  selector:
    matchLabels:
      app: logstash
      version: "1.0"
      environment: logging
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
        version: "1.0"
        environment: logging
    spec:
      containers:
      - name: logstash-container
        image: docker.elastic.co/logstash/logstash:7.4.1
        env:
          - name:  ELASTICSEARCH_HOST
            value: "elasticsearch-service.nl-amis-logging"
          - name:  ELASTICSEARCH_PORT
            value: "9200"
        ports:
        - containerPort: 5044
        volumeMounts:
          - name: logstash-settings-config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-config-volume
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: logstash-settings-config-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-config-volume
        configMap:
          name: logstash-configmap
          items:
            - key: pipeline.conf
              path: pipeline.conf
