apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksservice-v2.0
  namespace: nl-amis-development
  labels:
    app: booksservice
    version: "2.0"
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booksservice
      version: "2.0"
      environment: development
  template:
    metadata:
      labels:
        app: booksservice
        version: "2.0"
        environment: development
    spec:
      containers:
      - name: booksservice-v2-0-container
        image: booksservice:v2.0
        env:
        - name: spring.profiles.active
          value: "development"
        ports:
        - containerPort: 9090